Repository fluentassertions/fluentassertions, pull requests merged in 2022-12, with the labels that each got.

#2054 Add `ThatAre[Not]Abstract`, `ThatAre[Not]Static` and `ThatAre[Not]Virtual` to `PropertyInfoSelector`
  Src/FluentAssertions/Common/PropertyInfoExtensions.cs
  Src/FluentAssertions/Types/PropertyInfoSelector.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Types/PropertyInfoSelectorSpecs.cs
  docs/_pages/releases.md
Labels: feature

#2063 Document alternatives for collection order
  Src/FluentAssertions/Collections/StringCollectionAssertions.cs
Labels: documentation

#2044 Nested `AssertionScope`s do not print inner scope reportables
  Src/FluentAssertions/Execution/AssertionScope.cs
  Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.BeEquivalentTo.cs
  Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
  docs/_pages/releases.md
Labels: bug

#2058 Add `ThatAre[Not]Abstract` to `TypeSelector`
  Src/FluentAssertions/Types/TypeSelector.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
  docs/_pages/releases.md
Labels: feature

#2059 Add `ThatAre[Not]Sealed` to `TypeSelector.cs`
  Src/FluentAssertions/Types/TypeSelector.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
  docs/_pages/releases.md
Labels: feature

#2068 Use TheoryData
  Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
  Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Exceptions/ExceptionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Extensions/ObjectExtensionsSpecs.cs
  Tests/FluentAssertions.Specs/Formatting/EnumerableExtensionsSpecs.cs
  Tests/FluentAssertions.Specs/Formatting/MultidimensionalArrayFormatterSpecs.cs
  Tests/FluentAssertions.Specs/OccurrenceConstraintSpecs.cs
  Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
  Tests/FluentAssertions.Specs/Streams/StreamAssertionSpecs.cs
Labels: testing

#2067 Document that `PathMap` is currently not supported
  docs/_pages/introduction.md
Labels: documentation

#2075 Order strings with ordinal comparison
  Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
  Src/FluentAssertions/Collections/SubsequentOrderingAssertions.cs
  Src/FluentAssertions/Formatting/DefaultValueFormatter.cs
  Tests/FluentAssertions.Specs/Primitives/StringComparisonSpecs.cs
  docs/_pages/releases.md
Labels: enhancement

#2079 Improve performance of `IsTuple()`
  Src/FluentAssertions/Common/TypeExtensions.cs
Labels: performance
