Repository fluentassertions/fluentassertions, pull requests merged in 2022-03, with the labels that each got.

#1835 Determine caller name for `EnumAssertions.Be`
  Src/FluentAssertions/Primitives/EnumAssertions.cs
  Src/FluentAssertions/Primitives/NullableEnumAssertions.cs
  Tests/FluentAssertions.Specs/Primitives/EnumAssertionSpecs.cs
  docs/_pages/releases.md
Labels: enhancement

#1838 Ensure ExcludingMissingMembers doesn't undo usage of WithMapping
  Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
  Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs
  docs/_pages/releases.md
Labels: bug

#1822 Better support for NaN in numeric assertions on floats and doubles
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/Numeric/DoubleAssertions.cs
  Src/FluentAssertions/Numeric/FloatAssertions.cs
  Src/FluentAssertions/Numeric/NumericAssertions.cs
  Src/FluentAssertions/NumericAssertionsExtensions.cs
  Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
  docs/_pages/releases.md
Labels: bug

#1844 Adding support for .NET6 DateOnly struct
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/Formatting/DateOnlyValueFormatter.cs
  Src/FluentAssertions/Formatting/Formatter.cs
  Src/FluentAssertions/Primitives/DateOnlyAssertions.cs
  Src/FluentAssertions/Primitives/NullableDateOnlyAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/FluentAssertions.Specs/Primitives/DateOnlyAssertionSpecs.cs
  docs/_pages/releases.md
Labels: enhancement

#1858 WithMapping now works in equivalency assertions on collections
  Src/FluentAssertions/Common/MemberPath.cs
  Src/FluentAssertions/Equivalency/Matching/MappedPathMatchingRule.cs
  Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs
  docs/_pages/releases.md
Labels: bug

#1867 Better handling of NaN in nullable numeric assertions
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/Numeric/NullableDoubleAssertions.cs
  Src/FluentAssertions/Numeric/NullableFloatAssertions.cs
  Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
  docs/_pages/releases.md
Labels: bug

#1865 Extend NullableBooleanAssertions by NotBe()
  Src/FluentAssertions/Primitives/NullableBooleanAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Primitives/NullableBooleanAssertionSpecs.cs
  docs/_pages/releases.md
Labels: feature
