Repository fluentassertions/fluentassertions, pull requests merged in 2022-04, with the labels that each got.

#1873 Update documentation: Add missing tip for `ContainItemsAssignableTo<T>()`
  docs/_data/mstest-migration/collectionAssert.yml
Labels: documentation

#1859 Add difference to numeric assertion failure messages
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/Numeric/ByteAssertions.cs
  Src/FluentAssertions/Numeric/DecimalAssertions.cs
  Src/FluentAssertions/Numeric/DoubleAssertions.cs
  Src/FluentAssertions/Numeric/FloatAssertions.cs
  Src/FluentAssertions/Numeric/Int16Assertions.cs
  Src/FluentAssertions/Numeric/Int32Assertions.cs
  Src/FluentAssertions/Numeric/Int64Assertions.cs
  Src/FluentAssertions/Numeric/NullableByteAssertions.cs
  Src/FluentAssertions/Numeric/NullableDecimalAssertions.cs
  Src/FluentAssertions/Numeric/NullableDoubleAssertions.cs
  Src/FluentAssertions/Numeric/NullableFloatAssertions.cs
  Src/FluentAssertions/Numeric/NullableInt16Assertions.cs
  Src/FluentAssertions/Numeric/NullableInt32Assertions.cs
  Src/FluentAssertions/Numeric/NullableInt64Assertions.cs
  Src/FluentAssertions/Numeric/NullableSByteAssertions.cs
  Src/FluentAssertions/Numeric/NullableSingleAssertions.cs
  Src/FluentAssertions/Numeric/NullableUInt16Assertions.cs
  Src/FluentAssertions/Numeric/NullableUInt32Assertions.cs
  Src/FluentAssertions/Numeric/NullableUInt64Assertions.cs
  Src/FluentAssertions/Numeric/NumericAssertions.cs
  Src/FluentAssertions/Numeric/SByteAssertions.cs
  Src/FluentAssertions/Numeric/SingleAssertions.cs
  Src/FluentAssertions/Numeric/UInt16Assertions.cs
  Src/FluentAssertions/Numeric/UInt32Assertions.cs
  Src/FluentAssertions/Numeric/UInt64Assertions.cs
  Src/FluentAssertions/NumericAssertionsExtensions.cs
  Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllSatisfy.cs
  Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Numeric/NumericDifferenceAssertionsSpecs.cs
  Tests/FluentAssertions.Specs/Specialized/TaskCompletionSourceAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
  docs/_pages/releases.md
Labels: enhancement

#1875 Improve difference calculation of overflowing integrals
  Src/FluentAssertions/Numeric/ByteAssertions.cs
  Src/FluentAssertions/Numeric/DecimalAssertions.cs
  Src/FluentAssertions/Numeric/DoubleAssertions.cs
  Src/FluentAssertions/Numeric/Int16Assertions.cs
  Src/FluentAssertions/Numeric/Int32Assertions.cs
  Src/FluentAssertions/Numeric/Int64Assertions.cs
  Src/FluentAssertions/Numeric/NullableByteAssertions.cs
  Src/FluentAssertions/Numeric/NullableDecimalAssertions.cs
  Src/FluentAssertions/Numeric/NullableDoubleAssertions.cs
  Src/FluentAssertions/Numeric/NullableInt16Assertions.cs
  Src/FluentAssertions/Numeric/NullableInt32Assertions.cs
  Src/FluentAssertions/Numeric/NullableInt64Assertions.cs
  Src/FluentAssertions/Numeric/NullableSByteAssertions.cs
  Src/FluentAssertions/Numeric/NullableSingleAssertions.cs
  Src/FluentAssertions/Numeric/NullableUInt16Assertions.cs
  Src/FluentAssertions/Numeric/NullableUInt32Assertions.cs
  Src/FluentAssertions/Numeric/NullableUInt64Assertions.cs
  Src/FluentAssertions/Numeric/NumericAssertions.cs
  Src/FluentAssertions/Numeric/SByteAssertions.cs
  Src/FluentAssertions/Numeric/SingleAssertions.cs
  Src/FluentAssertions/Numeric/UInt16Assertions.cs
  Src/FluentAssertions/Numeric/UInt32Assertions.cs
  Src/FluentAssertions/Numeric/UInt64Assertions.cs
  Tests/FluentAssertions.Specs/Numeric/NumericDifferenceAssertionsSpecs.cs
Labels: enhancement

#1879 Update documentation for event monitoring at .netstandard2.0
  docs/_pages/eventmonitoring.md
Labels: documentation

#1812 Restore basic assertions for collections in System.Data
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/Common/ReadOnlyNonGenericCollectionWrapper.cs
  Src/FluentAssertions/DataColumnCollectionAssertionExtensions.cs
  Src/FluentAssertions/DataRowCollectionAssertionExtensions.cs
  Src/FluentAssertions/DataTableCollectionAssertionExtensions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Collections/Data/DataColumnCollectionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Collections/Data/DataRowCollectionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Collections/Data/DataTableCollectionAssertionSpecs.cs
  docs/_pages/data.md
  docs/_pages/releases.md
Labels: feature

#1827 Add the ability to exclude non-browsable members from equivalency tests
  Src/FluentAssertions/Equivalency/Execution/CollectionMemberAssertionOptionsDecorator.cs
  Src/FluentAssertions/Equivalency/Field.cs
  Src/FluentAssertions/Equivalency/IEquivalencyAssertionOptions.cs
  Src/FluentAssertions/Equivalency/IMember.cs
  Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
  Src/FluentAssertions/Equivalency/Property.cs
  Src/FluentAssertions/Equivalency/Selection/ExcludeNonBrowsableMembersRule.cs
  Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
  Src/FluentAssertions/Equivalency/Steps/StructuralEqualityEquivalencyStep.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/Benchmarks/CheckIfMemberIsBrowsable.cs
  Tests/Benchmarks/Program.cs
  Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
  Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
  docs/_pages/objectgraphs.md
  docs/_pages/releases.md
Labels: feature

#1782 Add `For`/`Exclude` to allow exclusion of members inside a collection
  Src/FluentAssertions/Common/MemberPath.cs
  Src/FluentAssertions/Common/MemberPathSegmentEqualityComparer.cs
  Src/FluentAssertions/Equivalency/EquivalencyAssertionOptions.cs
  Src/FluentAssertions/Equivalency/NestedExclusionOptionBuilder.cs
  Src/FluentAssertions/Equivalency/Selection/ExcludeMemberByPathSelectionRule.cs
  Src/FluentAssertions/Equivalency/Selection/SelectMemberByPathSelectionRule.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
  docs/_pages/objectgraphs.md
  docs/_pages/releases.md
Labels: feature

#1880 Add overload to `HaveElement()` to be able to assert on occurrences for `XDocument` and `XElement`
  Src/FluentAssertions/Xml/XDocumentAssertions.cs
  Src/FluentAssertions/Xml/XElementAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
  docs/_pages/releases.md
  docs/_pages/xml.md
Labels: feature, api-approved
