Repository fluentassertions/fluentassertions, pull requests merged in 2022-07, with the labels that each got.

#1953 Make For/Excluding work with nested paths
  Src/FluentAssertions/Common/MemberPath.cs
  Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
  docs/_pages/releases.md
Labels: bug

#1958 Add Enum.BeOneOf to the docs
  docs/_pages/enums.md
Labels: documentation

#1960 Avoid allocating sub-arrays in ContainInOrder
  Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
  Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.ContainInOrder.cs
Labels: performance
