Repository fluentassertions/fluentassertions, pull requests merged in 2023-01, with the labels that each got.

#2076 Improve `Guard` helper
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/AssertionOptions.cs
  Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
  Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
  Src/FluentAssertions/Collections/StringCollectionAssertions.cs
  Src/FluentAssertions/Common/Guard.cs
  Src/FluentAssertions/Common/ReadOnlyNonGenericCollectionWrapper.cs
  Src/FluentAssertions/Data/DataColumnAssertions.cs
  Src/FluentAssertions/Data/DataRowAssertions.cs
  Src/FluentAssertions/Data/DataSetAssertions.cs
  Src/FluentAssertions/Data/DataTableAssertions.cs
  Src/FluentAssertions/Equivalency/ConversionSelector.cs
  Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyAssertionOptions.cs
  Src/FluentAssertions/EventRaisingExtensions.cs
  Src/FluentAssertions/Execution/AssertionScope.cs
  Src/FluentAssertions/Execution/GivenSelector.cs
  Src/FluentAssertions/Numeric/ComparableTypeAssertions.cs
  Src/FluentAssertions/Numeric/NullableNumericAssertions.cs
  Src/FluentAssertions/Numeric/NumericAssertions.cs
  Src/FluentAssertions/NumericAssertionsExtensions.cs
  Src/FluentAssertions/ObjectAssertionsExtensions.cs
  Src/FluentAssertions/Primitives/DateTimeAssertions.cs
  Src/FluentAssertions/Primitives/DateTimeOffsetAssertions.cs
  Src/FluentAssertions/Primitives/ObjectAssertions.cs
  Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs
  Src/FluentAssertions/Primitives/SimpleTimeSpanAssertions.cs
  Src/FluentAssertions/Primitives/TimeOnlyAssertions.cs
  Src/FluentAssertions/Specialized/AssemblyAssertions.cs
  Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
  Src/FluentAssertions/Specialized/DelegateAssertions.cs
  Src/FluentAssertions/Specialized/ExceptionAssertions.cs
  Src/FluentAssertions/Specialized/ExecutionTime.cs
  Src/FluentAssertions/Specialized/ExecutionTimeAssertions.cs
  Src/FluentAssertions/Specialized/FunctionAssertionHelpers.cs
  Src/FluentAssertions/Specialized/FunctionAssertions.cs
  Src/FluentAssertions/Specialized/GenericAsyncFunctionAssertions.cs
  Src/FluentAssertions/TypeExtensions.cs
  Src/FluentAssertions/Types/MemberInfoAssertions.cs
  Src/FluentAssertions/Types/MethodBaseAssertions.cs
  Src/FluentAssertions/Types/MethodInfoAssertions.cs
  Src/FluentAssertions/Types/MethodInfoSelector.cs
  Src/FluentAssertions/Types/MethodInfoSelectorAssertions.cs
  Src/FluentAssertions/Types/PropertyInfoAssertions.cs
  Src/FluentAssertions/Types/PropertyInfoSelector.cs
  Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs
  Src/FluentAssertions/Types/TypeAssertions.cs
  Src/FluentAssertions/Types/TypeSelector.cs
  Src/FluentAssertions/Types/TypeSelectorAssertions.cs
  Src/FluentAssertions/Xml/XElementAssertions.cs
  Tests/FluentAssertions.Specs/Numeric/NullableNumericAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Primitives/TimeOnlyAssertionSpecs.cs
Labels: documentation

#2077 Update nugets
  Build/_build.csproj
  Src/FluentAssertions/FluentAssertions.csproj
  Tests/Approval.Tests/Approval.Tests.csproj
  Tests/Benchmarks/Benchmarks.csproj
  Tests/Benchmarks/UsersOfGetClosedGenericInterfaces.cs
  Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
  Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
  Tests/TestFrameworks/MSTestV2.Specs/MSTestV2.Specs.csproj
  Tests/TestFrameworks/MSpec.Specs/MSpec.Specs.csproj
  Tests/TestFrameworks/NUnit3.Specs/NUnit3.Specs.csproj
  Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
Labels: building

#2080 Optimize `IsRecord()`
  Src/FluentAssertions/Common/TypeExtensions.cs
Labels: performance

#2078 Add issue templates and api review process
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/01_bug_report.yml
  .github/ISSUE_TEMPLATE/02_api_proposal.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#2047 Add extensions for `OccurrenceConstraint` that reads more fluently
  Src/FluentAssertions/Extensions/OccurrenceConstraintExtensions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/OccurrenceConstraintSpecs.cs
  docs/_pages/releases.md
  docs/_pages/strings.md
Labels: feature

#2074 Add `Imply()` to `BooleanAssertions`
  Src/FluentAssertions/Primitives/BooleanAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Primitives/BooleanAssertionSpecs.cs
  docs/_pages/booleans.md
  docs/_pages/releases.md
Labels: feature

#2083 Add `ThatAre[Not]ValueTypes` method to `TypeSelector.cs`
  Src/FluentAssertions/Types/TypeSelector.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Types/TypeSelectorSpecs.cs
  docs/_pages/releases.md
Labels: feature

#2084 Set process dotnet cli language to en-US
  build.ps1
  build.sh
Labels: testing, building

#2086 Add `cSpell` to NUKE build pipeline
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/spellcheck.yml
  .gitignore
  .nuke/build.schema.json
  Build/Build.cs
  Build/_build.csproj
  CONTRIBUTING.md
  cSpell.json
  docs/README.md
  docs/_pages/collections.md
  docs/_pages/extensibility.md
  docs/_pages/strings.md
  docs/run.bat
  package.json
  yarn.lock
Labels: documentation, building

#2089 Optimize NUKE spell check
  .github/workflows/build.yml
  .github/workflows/spellcheck.yml
  .nuke/build.schema.json
  Build/Build.cs
  Build/_build.csproj
  package.json
Labels: building

#2082 Extend `ThatArePublicOrInternal` to also look at the setter of properties
  Src/FluentAssertions/Types/PropertyInfoSelector.cs
  Tests/FluentAssertions.Specs/Types/PropertyInfoSelectorSpecs.cs
  docs/_pages/releases.md
Labels: bug

#2092 Add process env variable `DOTNET_CLI_UI_LANGUAGE` also inside targets
  Build/Build.cs
Labels: building

#2009 Treat record structs as records
  Src/FluentAssertions/Common/TypeExtensions.cs
  Tests/FluentAssertions.Equivalency.Specs/RecordSpecs.cs
  Tests/FluentAssertions.Specs/Types/TypeExtensionsSpecs.cs
  docs/_pages/objectgraphs.md
  docs/_pages/releases.md
Labels: bug

#2093 Clean up `Build.cs`
  .github/workflows/build.yml
  .nuke/build.schema.json
  Build/Build.cs
  Build/Configuration.cs
  package.json
Labels: building

#2042 Add unit tests for better coverage in Execution namespace
  Src/FluentAssertions/Common/Configuration.cs
  Src/FluentAssertions/Common/Services.cs
  Src/FluentAssertions/Execution/TestFrameworkProvider.cs
  Src/FluentAssertions/Execution/XUnit2TestFramework.cs
  Tests/FluentAssertions.Equivalency.Specs/TypedDataSetSpecs.cs
  Tests/FluentAssertions.Specs/Execution/FallbackTestFrameworkTests.cs
  Tests/FluentAssertions.Specs/Execution/TestFrameworkProviderTests.cs
Labels: testing

#2115 Add code coverage to XUnit2.Specs
  Tests/TestFrameworks/XUnit2.Specs/XUnit2.Specs.csproj
Labels: testing

#2119 Add missing tests for `int.Seconds(TimeSpan)`
  Tests/FluentAssertions.Specs/Extensions/TimeSpanConversionExtensionSpecs.cs
Labels: testing

#2118 Add test summaries
  Build/Build.cs
Labels: building
