Repository fluentassertions/fluentassertions, pull requests merged in 2023-09, with the labels that each got.

#2304 Make Gitversion+GitRepository required
  Build/Build.cs
Labels: building

#2302 Drop support for .NET Core
  .github/ISSUE_TEMPLATE/01_bug_report.yml
  .nuke/build.schema.json
  Build/Build.cs
  README.md
  Src/FluentAssertions/Common/MemberPathSegmentEqualityComparer.cs
  Src/FluentAssertions/Common/Services.cs
  Src/FluentAssertions/FluentAssertions.csproj
  Src/FluentAssertions/Streams/BufferedStreamAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
  Tests/FluentAssertions.Specs/Common/TimeSpanExtensions.cs
  Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Exceptions/AsyncFunctionExceptionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Exceptions/FunctionExceptionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Exceptions/NotThrowSpecs.cs
  Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
  Tests/FluentAssertions.Specs/Specialized/TaskOfTAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Streams/BufferedStreamAssertionSpecs.cs
  docs/_config.yml
  docs/_data/navigation.yml
  docs/_pages/about.md
  docs/_pages/introduction.md
  docs/_pages/releases.md
  docs/_pages/upgradingtov7.md
  docs/index.html
Labels: breaking change

#2312 Fixed formatting error when checking nullable `DateTimeOffset` with `BeWithin`/`Before`
  Src/FluentAssertions/Primitives/DateTimeOffsetRangeAssertions.cs
  Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.cs
  docs/_pages/releases.md
Labels: bug

#2326 Use 'npm' for yarn packages.
  .github/dependabot.yml
Labels: building

#2318 Pass down the reason to inner `AssertionScope`
  Src/FluentAssertions/Execution/AssertionScope.cs
  Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs
  docs/_pages/releases.md
Labels: bug

#2321 Change `AllSatisfy` to succeed on empty collections
  Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
  Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.AllSatisfy.cs
  docs/_pages/releases.md
Labels: bug, breaking change

#2324 Add `ForConstraint` to `IAssertionScope`
  Src/FluentAssertions/Execution/AssertionScope.cs
  Src/FluentAssertions/Execution/ContinuedAssertionScope.cs
  Src/FluentAssertions/Execution/IAssertionScope.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Execution/AssertionScope.ChainingApiSpecs.cs
  docs/_pages/releases.md
Labels: enhancement, breaking change

#2350 Change `OnlyContain` to succeed on empty collections
  Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
  Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.OnlyContain.cs
  docs/_pages/releases.md
Labels: enhancement, breaking change
