Repository fluentassertions/fluentassertions, pull requests merged in 2023-08, with the labels that each got.

#2266 Add `NotContainItemsAssignableTo`
  Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Collections/CollectionAssertionSpecs.NotContainItemsAssignableTo.cs
  docs/_pages/collections.md
  docs/_pages/releases.md
Labels: feature

#2267 Removed all support for DataSet, DataTable, DataRow and such
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/AssertionOptions.cs
  Src/FluentAssertions/Common/ReadOnlyNonGenericCollectionWrapper.cs
  Src/FluentAssertions/Data/DataColumnAssertions.cs
  Src/FluentAssertions/Data/DataEquivalencyAssertionOptions.cs
  Src/FluentAssertions/Data/DataRowAssertions.cs
  Src/FluentAssertions/Data/DataSetAssertions.cs
  Src/FluentAssertions/Data/DataTableAssertions.cs
  Src/FluentAssertions/Data/IDataEquivalencyAssertionOptions.cs
  Src/FluentAssertions/Data/RowMatchMode.cs
  Src/FluentAssertions/DataColumnCollectionAssertionExtensions.cs
  Src/FluentAssertions/DataRowAssertionExtensions.cs
  Src/FluentAssertions/DataRowCollectionAssertionExtensions.cs
  Src/FluentAssertions/DataSetAssertionExtensions.cs
  Src/FluentAssertions/DataTableAssertionExtensions.cs
  Src/FluentAssertions/DataTableCollectionAssertionExtensions.cs
  Src/FluentAssertions/Equivalency/Steps/ConstraintCollectionEquivalencyStep.cs
  Src/FluentAssertions/Equivalency/Steps/ConstraintEquivalencyStep.cs
  Src/FluentAssertions/Equivalency/Steps/DataColumnEquivalencyStep.cs
  Src/FluentAssertions/Equivalency/Steps/DataRelationEquivalencyStep.cs
  Src/FluentAssertions/Equivalency/Steps/DataRowCollectionEquivalencyStep.cs
  Src/FluentAssertions/Equivalency/Steps/DataRowEquivalencyStep.cs
  Src/FluentAssertions/Equivalency/Steps/DataSetEquivalencyStep.cs
  Src/FluentAssertions/Equivalency/Steps/DataTableEquivalencyStep.cs
  Src/FluentAssertions/EquivalencyPlan.cs
  Src/FluentAssertions/FluentAssertions.csproj
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/Benchmarks/Benchmarks.csproj
  Tests/Benchmarks/LargeDataTableEquivalency.cs
  Tests/FluentAssertions.Equivalency.Specs/DataColumnSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/DataRelationSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/DataRowSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/DataSetSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/DataSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/FluentAssertions.Equivalency.Specs.csproj
  Tests/FluentAssertions.Equivalency.Specs/TypedDataSetSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/TypedDataTableSpecs.cs
  Tests/FluentAssertions.Specs/Collections/Data/DataColumnCollectionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Collections/Data/DataRowCollectionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Collections/Data/DataTableCollectionAssertionSpecs.cs
  Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
  docs/_pages/data.md
  docs/_pages/releases.md
Labels: breaking change

#2280 Add Dependabot
  .github/dependabot.yml
Labels: building
