Repository fluentassertions/fluentassertions, pull requests merged in 2023-10, with the labels that each got.

#2360 Decrease the Qodana `failThreshold`
  qodana.yaml
Labels: building

#2307 Improve failure message for string assertions when checking for equality
  Src/FluentAssertions/Common/StringExtensions.cs
  Src/FluentAssertions/Primitives/StringEqualityStrategy.cs
  Src/FluentAssertions/Primitives/StringValidator.cs
  Tests/FluentAssertions.Equivalency.Specs/BasicSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/CyclicReferencesSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/NestedPropertiesSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
  Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
  Tests/FluentAssertions.Specs/Formatting/FormatterSpecs.cs
  Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Primitives/StringAssertionSpecs.Be.cs
  Tests/FluentAssertions.Specs/Types/PropertyInfoAssertionSpecs.cs
  docs/_pages/releases.md
Labels: enhancement

#2370 Replace constructor with members initialized inline
  Src/FluentAssertions/Common/StopwatchTimer.cs
  Src/FluentAssertions/EquivalencyPlan.cs
Labels: building

#2354 Add a note to XML-docs that explains the `(Not)ContainEquivalentOf` problem
  Src/FluentAssertions/Collections/GenericCollectionAssertions.cs
Labels: documentation

#2371 Move non-generic `NotThrow[After]` to `ActionAssertions`
  Src/FluentAssertions/Specialized/ActionAssertions.cs
  Src/FluentAssertions/Specialized/DelegateAssertions.cs
  Src/FluentAssertions/Specialized/FunctionAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  docs/_pages/releases.md
Labels: breaking change

#2358 Handle comparing an `IDictionary` subject with an `IDictionary<,>` expectation
  Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
  Tests/FluentAssertions.Equivalency.Specs/DictionarySpecs.cs
  docs/_pages/releases.md
Labels: bug

#2329 Pass `FormattingOptions` to inner `AssertionScope`
  Src/FluentAssertions/Execution/AssertionScope.cs
  Tests/FluentAssertions.Specs/AssertionOptionsSpecs.cs
  Tests/FluentAssertions.Specs/Execution/AssertionScopeSpecs.cs
  docs/_pages/releases.md
Labels: bug

#2390 Capitalize true and false in failure messages
  Src/FluentAssertions/Primitives/BooleanAssertions.cs
  Tests/FluentAssertions.Specs/Primitives/BooleanAssertionSpecs.cs
  docs/_pages/releases.md
Labels: bug

#2389 Introduces an attribute to mark an entire assembly as one that contains custom assertions.
  FluentAssertions.sln
  Src/FluentAssertions/CallerIdentifier.cs
  Src/FluentAssertions/CustomAssertionsAssemblyAttribute.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/ExampleExtensions/AssemblyInfo.cs
  Tests/ExampleExtensions/ExampleExtensions.csproj
  Tests/ExampleExtensions/StringAssertionExtensions.cs
  Tests/FluentAssertions.Specs/ExtensibilitySpecs.cs
  Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
  docs/_pages/introduction.md
  docs/_pages/releases.md
Labels: enhancement

#2386 Allow specifying the build configuration.
  .nuke/build.schema.json
  Build/Build.cs
  Build/Configuration.cs
Labels: building

#2381 Simplify the ApiApproval test
  Tests/Approval.Tests/ApiApproval.cs
  Tests/Approval.Tests/Approval.Tests.csproj
Labels: building
