Repository fluentassertions/fluentassertions, pull requests merged in 2023-04, with the labels that each got.

#2163 Improve the `DataRowCollectionEquivalency` code coverage
  Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
Labels: testing

#2167 Improve the DateOnly and TimeOnly code coverage
  Tests/FluentAssertions.Specs/Primitives/DateOnlyAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Primitives/TimeOnlyAssertionSpecs.cs
Labels: testing

#2171 fix link to PR in release notes
  docs/_pages/releases.md
Labels: documentation

#2176 Prevent `InvalidOperationException` when formatting lambda expression
  Src/FluentAssertions/Formatting/PredicateLambdaExpressionValueFormatter.cs
  Tests/FluentAssertions.Specs/Formatting/PredicateLambdaExpressionValueFormatterSpecs.cs
  docs/_pages/releases.md
Labels: bug

#2178 Use builtin coveralls flag to ignore missing coverage file
  .github/workflows/build.yml
Labels: building

#2181 Do not interpret double braces as liquid template
  docs/_pages/releases.md
Labels: documentation

#2190 Github -> GitHub
  docs/README.md
  docs/_data/navigation.yml
  docs/index.html
Labels: documentation

#2193 Fix badge links
  README.md
Labels: documentation

#2191 Simplify `GenericDictionaryEquivalencyStep`
  Src/FluentAssertions/Equivalency/Steps/DictionaryInterfaceInfo.cs
  Src/FluentAssertions/Equivalency/Steps/GenericDictionaryEquivalencyStep.cs
Labels: testing
