Repository fluentassertions/fluentassertions, pull requests merged in 2023-03, with the labels that each got.

#2134 Add missing xml docs for parameters
  Src/FluentAssertions/DataColumnCollectionAssertionExtensions.cs
  Src/FluentAssertions/Specialized/ExceptionAssertions.cs
Labels: documentation

#2133 Increase robustness of assertions when wrapped in an `AssertionScope`
  Src/FluentAssertions/Collections/GenericDictionaryAssertions.cs
  Src/FluentAssertions/Data/DataRowAssertions.cs
  Src/FluentAssertions/Data/DataSetAssertions.cs
  Src/FluentAssertions/Data/DataTableAssertions.cs
  Src/FluentAssertions/Events/EventAssertions.cs
  Src/FluentAssertions/Xml/XDocumentAssertions.cs
  Src/FluentAssertions/Xml/XElementAssertions.cs
  Src/FluentAssertions/Xml/XmlElementAssertions.cs
  Tests/FluentAssertions.Equivalency.Specs/DataRowSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/DataSetSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/DataTableSpecs.cs
  Tests/FluentAssertions.Specs/Collections/GenericDictionaryAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Events/EventAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Xml/XDocumentAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Xml/XElementAssertionSpecs.cs
  Tests/FluentAssertions.Specs/Xml/XmlElementAssertionSpecs.cs
  docs/_pages/releases.md
Labels: bug

#1974 Added `ThrowWithinAsync` assertions
  Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs
  Src/FluentAssertions/Specialized/DelegateAssertionsBase.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs
  docs/_pages/executiontime.md
  docs/_pages/releases.md
Labels: feature

#2153 Fix xml docs for time-related assertions
  Src/FluentAssertions/Primitives/NullableDateOnlyAssertions.cs
  Src/FluentAssertions/Primitives/NullableDateTimeAssertions.cs
  Src/FluentAssertions/Primitives/NullableTimeOnlyAssertions.cs
Labels: documentation

#2151 Add WithoutStrictOrderingFor overload with an expression
  Src/FluentAssertions/Equivalency/EquivalencyAssertionOptions.cs
  Src/FluentAssertions/Equivalency/Ordering/PathBasedOrderingRule.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp2.1.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netcoreapp3.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs
  docs/_pages/releases.md
Labels: feature
