Repository fluentassertions/fluentassertions, pull requests merged in 2024-01, with the labels that each got.

#2537 Bump cspell to 8.3.2
  yarn.lock
Labels: building

#2536 Add missing `NotBeIn(DateTimeKind)` `DateTime` assertion
  Src/FluentAssertions/Primitives/DateTimeAssertions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/Primitives/DateTimeAssertionSpecs.BeIn.cs
  docs/_pages/datetimespans.md
  docs/_pages/releases.md
Labels: feature

#2380 Add [NotNull] attribute on the Should() method for object assertions
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/XmlAssertionExtensions.cs
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/FluentAssertions.Specs/AssertionExtensionsSpecs.cs
  docs/_pages/releases.md
Labels: enhancement
