Repository fluentassertions/fluentassertions, pull requests merged in 2025-09, with the labels that each got.

#3084 Add lock file for nuget packages
  Build/Build.cs
  Build/packages.lock.json
  Directory.Build.props
  Src/FluentAssertions/packages.lock.json
  Tests/Approval.Tests/packages.lock.json
  Tests/AssemblyA/packages.lock.json
  Tests/AssemblyB/packages.lock.json
  Tests/Benchmarks/packages.lock.json
  Tests/ExampleExtensions/packages.lock.json
  Tests/FSharp.Specs/FSharp.Specs.fsproj
  Tests/FSharp.Specs/packages.lock.json
  Tests/FluentAssertions.Equivalency.Specs/packages.lock.json
  Tests/FluentAssertions.Extensibility.Specs/packages.lock.json
  Tests/FluentAssertions.Specs/packages.lock.json
  Tests/TestFrameworks/MSTestV2.Specs/packages.lock.json
  Tests/TestFrameworks/MSpec.Specs/packages.lock.json
  Tests/TestFrameworks/NUnit3.Specs/packages.lock.json
  Tests/TestFrameworks/NUnit4.Specs/packages.lock.json
  Tests/TestFrameworks/TUnit.Specs/packages.lock.json
  Tests/TestFrameworks/XUnit2.Specs/packages.lock.json
  Tests/TestFrameworks/XUnit3.Specs/packages.lock.json
  Tests/TestFrameworks/XUnit3Core.Specs/packages.lock.json
  Tests/VB.Specs/packages.lock.json
Labels: building

#3094 Added System.Text.Json assertion APIs and BeEquivalentTo support
  .packageguard/cache.bin
  Src/FluentAssertions/AssertionExtensions.cs
  Src/FluentAssertions/Equivalency/EquivalencyOptions.cs
  Src/FluentAssertions/Equivalency/EquivalencyPlan.cs
  Src/FluentAssertions/Equivalency/Execution/CollectionMemberOptionsDecorator.cs
  Src/FluentAssertions/Equivalency/IEquivalencyOptions.cs
  Src/FluentAssertions/Equivalency/IMemberMatchingRule.cs
  Src/FluentAssertions/Equivalency/INode.cs
  Src/FluentAssertions/Equivalency/JsonProperty.cs
  Src/FluentAssertions/Equivalency/Matching/MustMatchByNameRule.cs
  Src/FluentAssertions/Equivalency/Matching/MustMatchJsonPropertyByNameRule.cs
  Src/FluentAssertions/Equivalency/Matching/MustMatchMemberByNameRule.cs
  Src/FluentAssertions/Equivalency/Matching/TryMatchByNameRule.cs
  Src/FluentAssertions/Equivalency/Matching/TryMatchJsonPropertyByNameRule.cs
  Src/FluentAssertions/Equivalency/Matching/TryMatchMemberByNameRule.cs
  Src/FluentAssertions/Equivalency/Node.cs
  Src/FluentAssertions/Equivalency/Pathway.cs
  Src/FluentAssertions/Equivalency/SelfReferenceEquivalencyOptions.cs
  Src/FluentAssertions/Equivalency/Steps/JsonConversionStep.cs
  Src/FluentAssertions/Formatting/Formatter.cs
  Src/FluentAssertions/Formatting/JsonNodeFormatter.cs
  Src/FluentAssertions/Specialized/JsonNodeAssertions.cs
  Tests/.editorconfig
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net47.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/net6.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.0.verified.txt
  Tests/Approval.Tests/ApprovedApi/FluentAssertions/netstandard2.1.verified.txt
  Tests/ExampleExtensions/ExampleExtensions.csproj
  Tests/FluentAssertions.Equivalency.Specs/BasicSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/JsonNodeSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/NestedPropertiesSpecs.cs
  Tests/FluentAssertions.Equivalency.Specs/SelectionRulesSpecs.cs
  Tests/FluentAssertions.Extensibility.Specs/ExtensibilitySpecs.cs
  Tests/FluentAssertions.Extensibility.Specs/FluentAssertions.Extensibility.Specs.csproj
  Tests/FluentAssertions.Extensibility.Specs/HttpResponseMessageAssertions.cs
  Tests/FluentAssertions.Extensibility.Specs/JsonWithInlineAssertionsSpecs.cs
  Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj
  Tests/FluentAssertions.Specs/Formatting/JsonFormatterSpecs.cs
  Tests/FluentAssertions.Specs/Specialized/JsonNodeSpecs.cs
  docs/_data/navigation.yml
  docs/_pages/json.md
  docs/_pages/objectgraphs.md
  docs/_pages/releases.md
Labels: feature

#3104 Add docs for `config` parameter
  Src/FluentAssertions/Specialized/JsonNodeAssertions.cs
Labels: documentation
